# Generated by Django 6.0.4 on 2026-04-22 13:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_empresa_cnpj_empresa_endereco_funcionario'),
    ]

    operations = [
        migrations.AddField(
            model_name='funcionario',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
